In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
import os
os.chdir('/content/drive/MyDrive/Colab_Code')

In [3]:
#EDA package
import numpy as np
import pandas as pd

In [42]:
#CSV access
df = pd.read_csv("/content/drive/MyDrive/Colab_Code/olympics.csv",)

In [44]:
#rename - Multiple columns in a list
new_names =  { 'Unnamed: 0': 'Country',
               '? Summer': 'Summer',
               '01 !' : 'Gold_s',
               '02 !': 'Silver_s',
               '03 !': 'Bronze_s',
               'Total': 'Total_Summer',
               '? Winter' : 'Winter',
               '01 !.1': 'Gold_w',
               '02 !.1': 'Silver_w',
               '03 !.1': 'Bronze_w',
               'Total.1' : 'Total_Winter',
               '? Games': 'Total_Games',
               '01 !.2': 'Tot_Gold',
               '02 !.2': 'Tot_Sil',
               '03 !.2': 'Tot_Bro',
               'Combined total' : 'Combined_Total'}

In [45]:
#Change names of columns
df.rename(columns=new_names, inplace=True)

In [ ]:
df.head(3)

In [ ]:
#Types of information
data_types = df.dtypes
print(data_types)

In [ ]:
#Check null values
df.isnull().any()

In [ ]:
#Clean the Country
df['Country'] = df['Country'].str.split(pat='(').str[0]
df

In [32]:
df.describe()

,Summer,Gold_s,Silver_s,Bronze_s,Total_Summer,Winter,Gold_w,Silver_w,Bronze_w,Total_Winter,Total_Games,Tot_Gold,Tot_Sil,Tot_Bro,Combined_Total,IOC
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,0.0
mean,13.476190,65.428571,64.965986,69.795918,200.190476,6.700680,13.047619,13.034014,12.897959,38.979592,20.176871,78.476190,78.000000,82.693878,239.170068,NaN
std,7.072359,405.549990,399.309960,427.187344,1231.306297,7.433186,80.799204,80.634421,79.588388,240.917324,13.257048,485.013378,478.860334,505.855110,1469.067883,NaN
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,NaN
25%,8.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,1.000000,1.000000,2.500000,NaN
50%,13.000000,3.000000,4.000000,6.000000,12.000000,5.000000,0.000000,0.000000,0.000000,0.000000,15.000000,3.000000,4.000000,7.000000,12.000000,NaN
75%,18.500000,24.000000,28.000000,29.000000,86.000000,10.000000,1.000000,2.000000,1.000000,5.000000,27.000000,25.500000,29.000000,32.500000,89.000000,NaN
max,27.000000,4809.000000,4775.000000,5130.000000,14714.000000,22.000000,959.000000,958.000000,948.000000,2865.000000,49.000000,5768.000000,5733.000000,6078.000000,17579.000000,NaN